version: "3"
services:
  p2-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=toktik-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresdata1:/var/lib/postgres/
    ports:
      - "5432:5432"
    networks:
      - db-network
  
  p2-frontend:
    image: ghcr.io/scalable-23t1-p2-toktik/frontend/scalable-p2-frontend:latest
    environment:
      - DATABASE_URL=postgres://postgres:password@p2-db:5432/toktik-database
      - NEXTAUTH_SECRET=toktik
      - SOCKET_IO_HOSTNAME=p2-notification
    depends_on:
      - p2-db
      - redis
    ports:
      - "3000:3000"
    networks:
      - db-network
      - gateway
  
  p2-backend:
    image: ghcr.io/scalable-23t1-p2-toktik/backend/scalable-p2-backend:latest
    environment:
      - BACKEND_DB_NAME=toktik-database
      - BACKEND_DB_USERNAME=postgres
      - BACKEND_DB_PASSWORD=password
      - BACKEND_DB_PORT=5432
      - BACKEND_DB_IP=p2-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - p2-db
      - redis
    ports:
      - "8080:8080"
    networks:
      - db-network
      - gateway
      - redis_network
  
  p2-notification:
    image: ghcr.io/scalable-23t1-p2-toktik/notification-service/scalable-p2-notification:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - p2-frontend
      - p2-backend
    ports:
      - "5000:5000"
    networks:
      - gateway
      - redis_network

  p2-proxy:
    image: nginx:1.21
    ports:
      - "80:80"
    depends_on:
      - p2-frontend
      - p2-backend
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - gateway
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - gateway
      - redis_network

  p2-ffmpeg:
     image: ghcr.io/scalable-23t1-p2-toktik/ffmpeg-worker/scalable-p2-ffmpeg-worker:latest
     environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=AKIAUBKTRWRI7PJUFDQV
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
     depends_on:
      - redis
     networks:
      - redis_network
  
volumes:
    postgresdata1:
      driver: local

networks:
  db-network:
  gateway:
    driver: bridge
  redis_network: