apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-frontend
        image: busybox
        command: ['sh', '-c', 'sleep 60']
      containers:
      - name: backend
        image: ghcr.io/scalable-23t1-p2-toktik/backend/scalable-p2-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-service.default.svc
        - name: REDIS_PORT
          value: "6379"
        - name: BACKEND_DB_IP
          value: postgres-service.default.svc
        - name: BACKEND_DB_PORT
          value: "5432"
        - name: BACKEND_DB_NAME
          value: "toktik-database"
        - name: BACKEND_DB_USERNAME
          value: "postgres"
        - name: BACKEND_DB_PASSWORD
          value: "password"
        - name: SOCKET_IO_HOSTNAME
          value: notification.default.svc
        - name: AWS_REGION
          value: ap-southeast-2
        - name: AWS_ACCESS_KEY_ID
          value: AKIAUBKTRWRI7PJUFDQV
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
      
      imagePullSecrets:
      - name: regcred
