apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-thumbnailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg-thumbnailer
  template:
    metadata:
      labels:
        app: ffmpeg-thumbnailer
    spec:
      containers:
      - name: ffmpeg-thumbnailer
        image: ghcr.io/scalable-23t1-p2-toktik/ffmpeg-worker/scalable-p2-ffmpeg-thumbnailer:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: ffmpeg-storage
          mountPath: /pv
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        envFrom:
          - secretRef:
              name: ffmpeg-secrets
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: ffmpeg-storage
        persistentVolumeClaim:
          claimName: ffmpeg-pvc

