apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ffmpeg-converter
  template:
    metadata:
      labels:
        app: ffmpeg-converter
    spec:
      containers:
      - name: ffmpeg-converter
        image: ghcr.io/scalable-23t1-p2-toktik/ffmpeg-worker/scalable-p2-ffmpeg-converter:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        envFrom:
          - secretRef:
              name: ffmpeg-secrets
      imagePullSecrets:
      - name: regcred

