apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/scalable-23t1-p2-toktik/frontend/scalable-p2-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: "postgres://postgres:password@postgres-service.default.svc:5432/toktik-database"
          - name: NEXTAUTH_SECRET
            value: "toktik"
          - name: BACKEND_HOSTNAME
            value: backend.default.svc
          - name: SOCKET_IO_HOSTNAME
            value: notification.default.svc
          # - name: NEXTAUTH_URL
          #   value: frontend.default.svc
      imagePullSecrets:
      - name: regcred