apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "toktik-database"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: PG_PORT
          value: "5433"
        volumeMounts:
        - name: postgres-pv
          mountPath: "/var/lib/mysql"
        ports:
        - containerPort: 5432

      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc